runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

inbound_services:
- warmup

automatic_scaling:
  max_instances: 100
  min_idle_instances: 1
  min_pending_latency: 10ms
